<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eco Trans Systems</title>
    <link rel="stylesheet" href="css\styles.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="IMG\favicon_io\favicon.ico">
    <link rel="apple-touch-icon" sizes="180x180" href="IMG\favicon_io\apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="IMG\favicon_io\favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="IMG\favicon_io\favicon-16x16.png">
    <link rel="manifest" href="IMG\favicon_io\site.webmanifest">
    <style>
        .center {
            display: flex;
            justify-content: center;
        }
    </style>
</head>

<body>
    <header>
        <h1>Eco Trans Systems</h1>
    </header>
    <nav>
        <ul>
            <li class="texto-con-sombra"><a href="{{ route('index') }}">Home</a></li>
            <li class="texto-con-sombra"><a href="{{ route('nosotros') }}">Nosotros</a></li>
            <li class="texto-con-sombra"><a href="{{ route('servicios') }}">Servicios</a></li>
            <li class="texto-con-sombra"><a href="{{ route('contacto') }}">Contacto</a></li>
            <li class="texto-con-sombra"><a href="{{ route('estadisticas') }}">Reportes</a></li>
            <li class="texto-con-sombra"><a href="{{ route('historial') }}">Historial</a></li>
            <li class="texto-con-sombra"><a href="{{ route('flota') }}">Flota</a></li>
            <li class="texto-con-sombra"><a href="{{ route('login') }}">Login</a></li>
            <li class="texto-con-sombra"><a href="{{ route('register') }}">Registro</a></li>
        </ul>
    </nav>
    <main id="main">
        <div class="container mt-5">
            <h2>Generar Flota</h2>
            <!-- Selección del tipo de vehículo -->
            <div class="form-group">
                <label for="tipoVehiculo">Seleccionar Tipo de Vehículo:</label>
                <select id="tipoVehiculo" class="form-control" onchange="mostrarHistorial()">
                    <option value="">Selecciona el tipo de vehículo</option>
                    <option value="bicicletas">Bicicletas</option>
                    <option value="patinetas">Patines eléctricos</option>
                    <option value="skateboards">Skateboards</option>
                </select>
            </div>

            <!-- Historial -->
            <div id="historialBicicletas" class="hidden">
                <h3>Historial de Bicicletas</h3>
                <p>Aquí se mostrará el historial de bicicletas.</p>
                <!-- Añadir contenido relevante del historial de bicicletas -->
                <style>
                    .table {
                      border-collapse: separate;
                      border-spacing: 0 10px;
                      width: 100%;
                    }
                    .table th,
                    .table td {
                      padding: 8px;
                      text-align: left;
                      border-bottom: 1px solid #ddd;
                    }
                    .table th {
                      background-color: #f2f2f2;
                      color: black;
                      border-top: 1px solid #ddd;
                    }
                    .table tbody tr:nth-child(even) {
                      background-color: #f2f2f2;
                    }
                    .table tbody tr:hover {
                      background-color: #ddd;
                    }
                  </style>
                  
                  <table class="table">
                    <thead class="thead-dark">
                      <tr>
                        <th scope="col">Total</th>
                        <th scope="col">Alquiladas</th>
                        <th scope="col">Disponibles</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>500</td>
                            <td>70</td>
                            <td>430</td>
                        </tr>
                    </tbody>
                  </table>
                  <table class="table">
                    <thead class="thead-dark">
                        <tr>
                          <th scope="col">Nombre</th>
                          <th scope="col">Apellido</th>
                          <th scope="col">Cédula</th>
                          <th scope="col">Fecha de Inicio</th>
                          <th scope="col">Duración (días)</th>
                        </tr>
                    </thead>
                    <tbody>
                      <tr>
                      <td>Elena</td>
                      <td>González</td>
                      <td>01234567</td>
                      <td>20-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Daniel</td>
                      <td>Díaz</td>
                      <td>01234567</td>
                      <td>20-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Patricia</td>
                      <td>Sánchez</td>
                      <td>45678901</td>
                      <td>20-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Javier</td>
                      <td>Martínez</td>
                      <td>23456789</td>
                      <td>20-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Claudia</td>
                      <td>Martínez</td>
                      <td>23456789</td>
                      <td>20-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Carmen</td>
                      <td>Martínez</td>
                      <td>23456789</td>
                      <td>20-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Luisa</td>
                      <td>Martínez</td>
                      <td>23456789</td>
                      <td>20-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>María</td>
                      <td>Hernández</td>
                      <td>89012345</td>
                      <td>20-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Juan</td>
                      <td>Hernández</td>
                      <td>89012345</td>
                      <td>20-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Francisco</td>
                      <td>Hernández</td>
                      <td>56789012</td>
                      <td>20-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Andrea</td>
                      <td>Hernández</td>
                      <td>56789012</td>
                      <td>20-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Luis</td>
                      <td>Fernández</td>
                      <td>78901234</td>
                      <td>20-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Isabel</td>
                      <td>Jiménez</td>
                      <td>45678901</td>
                      <td>20-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Francisco</td>
                      <td>Vargas</td>
                      <td>56789012</td>
                      <td>20-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Elena</td>
                      <td>Vargas</td>
                      <td>56789012</td>
                      <td>20-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Diego</td>
                      <td>Vargas</td>
                      <td>56789012</td>
                      <td>20-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Patricia</td>
                      <td>Vargas</td>
                      <td>56789012</td>
                      <td>20-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Sofía</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>20-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Elena</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>20-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Juan</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>20-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Ernesto</td>
                      <td>Santos</td>
                      <td>86913473</td>
                      <td>20-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Laura</td>
                      <td>Rodríguez</td>
                      <td>45678901</td>
                      <td>19-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Patricia</td>
                      <td>Rodríguez</td>
                      <td>34567890</td>
                      <td>19-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Juan</td>
                      <td>Rodríguez</td>
                      <td>34567890</td>
                      <td>19-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Andrés</td>
                      <td>Torres</td>
                      <td>34567890</td>
                      <td>19-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Alejandro</td>
                      <td>Ramírez</td>
                      <td>90123456</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Sergio</td>
                      <td>Martínez</td>
                      <td>34567890</td>
                      <td>19-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Adriana</td>
                      <td>Rodríguez</td>
                      <td>34567890</td>
                      <td>19-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Raúl</td>
                      <td>Rodríguez</td>
                      <td>34567890</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Florencia</td>
                      <td>Álvarez</td>
                      <td>64897538</td>
                      <td>19-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Jaime</td>
                      <td>Lara</td>
                      <td>31486976</td>
                      <td>19-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Ignacio</td>
                      <td>Mendoza</td>
                      <td>53148691</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Rebeca</td>
                      <td>Vega</td>
                      <td>20975317</td>
                      <td>19-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Maximiliano</td>
                      <td>Soto</td>
                      <td>20975319</td>
                      <td>19-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Isidora</td>
                      <td>Molina</td>
                      <td>86913465</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Vicente</td>
                      <td>Aguilar</td>
                      <td>75314866</td>
                      <td>19-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Andrés</td>
                      <td>Castro</td>
                      <td>78901234</td>
                      <td>19-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Sofía</td>
                      <td>González</td>
                      <td>90123456</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Laura</td>
                      <td>González</td>
                      <td>90123456</td>
                      <td>19-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Marcos</td>
                      <td>Flores</td>
                      <td>90123456</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Carlos</td>
                      <td>Flores</td>
                      <td>89012345</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Mario</td>
                      <td>Sánchez</td>
                      <td>45678901</td>
                      <td>19-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Elena</td>
                      <td>Sánchez</td>
                      <td>34567890</td>
                      <td>19-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Luisa</td>
                      <td>Sánchez</td>
                      <td>45678901</td>
                      <td>19-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Carlos</td>
                      <td>Martínez</td>
                      <td>34567890</td>
                      <td>18-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Cristina</td>
                      <td>Torres</td>
                      <td>01234567</td>
                      <td>18-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Emilia</td>
                      <td>Castillo</td>
                      <td>75314869</td>
                      <td>18-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Benjamín</td>
                      <td>Fuentes</td>
                      <td>64897535</td>
                      <td>18-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Antonia</td>
                      <td>Campos</td>
                      <td>53148694</td>
                      <td>18-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Matías</td>
                      <td>Ortega</td>
                      <td>42975311</td>
                      <td>18-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Renata</td>
                      <td>Parra</td>
                      <td>31486978</td>
                      <td>18-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Marcos</td>
                      <td>Hernández</td>
                      <td>89012345</td>
                      <td>18-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Valeria</td>
                      <td>Mora</td>
                      <td>20975316</td>
                      <td>17-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Joaquín</td>
                      <td>Vásquez</td>
                      <td>86913472</td>
                      <td>17-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Gabriela</td>
                      <td>Contreras</td>
                      <td>42975318</td>
                      <td>17-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Santiago</td>
                      <td>Espinoza</td>
                      <td>31486972</td>
                      <td>17-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Iván</td>
                      <td>González</td>
                      <td>78901234</td>
                      <td>17-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Silvia</td>
                      <td>Castro</td>
                      <td>78901234</td>
                      <td>17-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Pablo</td>
                      <td>Martín</td>
                      <td>34567890</td>
                      <td>17-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Carolina</td>
                      <td>Martínez</td>
                      <td>90123456</td>
                      <td>17-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Pablo</td>
                      <td>González</td>
                      <td>90123456</td>
                      <td>17-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Elena</td>
                      <td>González</td>
                      <td>90123456</td>
                      <td>17-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Laura</td>
                      <td>González</td>
                      <td>67890123</td>
                      <td>17-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Andrea</td>
                      <td>Castro</td>
                      <td>78901234</td>
                      <td>17-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Francisco</td>
                      <td>Castro</td>
                      <td>45678901</td>
                      <td>17-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Javier</td>
                      <td>Flores</td>
                      <td>12345678</td>
                      <td>17-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Paula</td>
                      <td>Flores</td>
                      <td>89012345</td>
                      <td>17-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Carmen</td>
                      <td>Rodríguez</td>
                      <td>34567890</td>
                      <td>17-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Manuel</td>
                      <td>Rodríguez</td>
                      <td>34567890</td>
                      <td>17-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Juan</td>
                      <td>Vargas</td>
                      <td>56789012</td>
                      <td>17-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Elena</td>
                      <td>Hernández</td>
                      <td>56789012</td>
                      <td>17-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Diego</td>
                      <td>Hernández</td>
                      <td>56789012</td>
                      <td>17-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>María</td>
                      <td>González</td>
                      <td>23456789</td>
                      <td>16-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Patricia</td>
                      <td>Sánchez</td>
                      <td>45678901</td>
                      <td>16-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Javier</td>
                      <td>Vargas</td>
                      <td>56789012</td>
                      <td>16-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Laura</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>16-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Pablo</td>
                      <td>Castro</td>
                      <td>78901234</td>
                      <td>16-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Carolina</td>
                      <td>Hernández</td>
                      <td>89012345</td>
                      <td>16-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Paula</td>
                      <td>Hernández</td>
                      <td>89012345</td>
                      <td>16-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Sergio</td>
                      <td>Flores</td>
                      <td>12345678</td>
                      <td>16-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Adriana</td>
                      <td>Díaz</td>
                      <td>01234567</td>
                      <td>16-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Laura</td>
                      <td>Díaz</td>
                      <td>01234567</td>
                      <td>16-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Carlos</td>
                      <td>Díaz</td>
                      <td>01234567</td>
                      <td>16-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>María</td>
                      <td>Díaz</td>
                      <td>78901234</td>
                      <td>16-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Juan</td>
                      <td>Castro</td>
                      <td>78901234</td>
                      <td>16-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Elena</td>
                      <td>Castro</td>
                      <td>45678901</td>
                      <td>16-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Francisco</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>16-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Andrea</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>16-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Patricia</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>16-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Raúl</td>
                      <td>Martínez</td>
                      <td>23456789</td>
                      <td>16-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Patricia</td>
                      <td>Martínez</td>
                      <td>23456789</td>
                      <td>16-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Isabela</td>
                      <td>Muñoz</td>
                      <td>53148692</td>
                      <td>15-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Tomás</td>
                      <td>Rojas</td>
                      <td>42975316</td>
                      <td>15-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Pedro</td>
                      <td>González</td>
                      <td>56789012</td>
                      <td>14-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Marina</td>
                      <td>Sánchez</td>
                      <td>01234567</td>
                      <td>14-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Adriana</td>
                      <td>Rodríguez</td>
                      <td>45678901</td>
                      <td>14-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Raúl</td>
                      <td>González</td>
                      <td>56789012</td>
                      <td>14-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Carmen</td>
                      <td>Sánchez</td>
                      <td>23456789</td>
                      <td>14-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Silvia</td>
                      <td>Herrera</td>
                      <td>89012345</td>
                      <td>14-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Iván</td>
                      <td>Díaz</td>
                      <td>01234567</td>
                      <td>14-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Paula</td>
                      <td>Díaz</td>
                      <td>01234567</td>
                      <td>14-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Claudia</td>
                      <td>Rodríguez</td>
                      <td>01234567</td>
                      <td>14-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Pablo</td>
                      <td>Rodríguez</td>
                      <td>34567890</td>
                      <td>14-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Laura</td>
                      <td>Hernández</td>
                      <td>89012345</td>
                      <td>14-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Pablo</td>
                      <td>Hernández</td>
                      <td>89012345</td>
                      <td>14-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Carolina</td>
                      <td>Hernández</td>
                      <td>89012345</td>
                      <td>14-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Andrea</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>14-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Francisco</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>14-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Elena</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>14-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Laura</td>
                      <td>Moreno</td>
                      <td>67890123</td>
                      <td>14-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Pablo</td>
                      <td>Martínez</td>
                      <td>23456789</td>
                      <td>14-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Laura</td>
                      <td>Martínez</td>
                      <td>23456789</td>
                      <td>14-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Carmen</td>
                      <td>Martínez</td>
                      <td>23456789</td>
                      <td>14-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Juan</td>
                      <td>López</td>
                      <td>34567890</td>
                      <td>14-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>María</td>
                      <td>Rodríguez</td>
                      <td>78901234</td>
                      <td>14-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Martín</td>
                      <td>García</td>
                      <td>89012345</td>
                      <td>14-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Marcos</td>
                      <td>Flores</td>
                      <td>12345678</td>
                      <td>14-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Isabel</td>
                      <td>Sánchez</td>
                      <td>23456789</td>
                      <td>14-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Diego</td>
                      <td>Rojas</td>
                      <td>56789012</td>
                      <td>14-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Sofía</td>
                      <td>González</td>
                      <td>89012345</td>
                      <td>14-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Valentina</td>
                      <td>Martínez</td>
                      <td>90123456</td>
                      <td>14-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Mateo</td>
                      <td>Gómez</td>
                      <td>34567890</td>
                      <td>14-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Sara</td>
                      <td>López</td>
                      <td>56789012</td>
                      <td>14-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Luis</td>
                      <td>Martínez</td>
                      <td>56789012</td>
                      <td>13-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Camila</td>
                      <td>González</td>
                      <td>67890123</td>
                      <td>13-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Emilia</td>
                      <td>Rodríguez</td>
                      <td>89012345</td>
                      <td>13-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Lucas</td>
                      <td>Moreno</td>
                      <td>90123456</td>
                      <td>13-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Valentín</td>
                      <td>Rojas</td>
                      <td>01234567</td>
                      <td>13-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Martina</td>
                      <td>Martínez</td>
                      <td>12345678</td>
                      <td>13-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Bruno</td>
                      <td>Flores</td>
                      <td>23456789</td>
                      <td>13-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Antonella</td>
                      <td>García</td>
                      <td>34567890</td>
                      <td>13-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Martín</td>
                      <td>Gómez</td>
                      <td>45678901</td>
                      <td>13-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Mateo</td>
                      <td>Rodríguez</td>
                      <td>56789012</td>
                      <td>13-05-2024</td>
                      <td>3</td>
                      </tr>                                                                                       
                    </tbody>
                </table>
            </div>

            <div id="historialPatinetas" class="hidden">
                <h3>Historial de Patines eléctricos</h3>
                <p>Aquí se mostrará el historial de Patines eléctricos.</p>
                <!-- Añadir contenido relevante del historial de patinetas -->
                <style>
                    .table {
                      border-collapse: separate;
                      border-spacing: 0 10px;
                      width: 100%;
                    }
                    .table th,
                    .table td {
                      padding: 8px;
                      text-align: left;
                      border-bottom: 1px solid #ddd;
                    }
                    .table th {
                      background-color: #f2f2f2;
                      color: black;
                      border-top: 1px solid #ddd;
                    }
                    .table tbody tr:nth-child(even) {
                      background-color: #f2f2f2;
                    }
                    .table tbody tr:hover {
                      background-color: #ddd;
                    }
                  </style>
                  
                  <table class="table">
                    <thead class="thead-dark">
                      <tr>
                        <th scope="col">Total</th>
                        <th scope="col">Alquiladas</th>
                        <th scope="col">Disponibles</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>250</td>
                            <td>30</td>
                            <td>220</td>
                        </tr>
                    </tbody>
                  </table>
                  <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">Cédula</th>
                            <th scope="col">Fecha de Inicio</th>
                            <th scope="col">Duración (días)</th>
                          </tr>
                    </thead>
                    <tbody>
                      <tr>
                      <td>Juan</td>
                      <td>González</td>
                      <td>12345678</td>
                      <td>20-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Carolina</td>
                      <td>Martínez</td>
                      <td>89012345</td>
                      <td>20-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Lucas</td>
                      <td>Martínez</td>
                      <td>90123456</td>
                      <td>20-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Andrés</td>
                      <td>López</td>
                      <td>56789012</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Sofía</td>
                      <td>Hernández</td>
                      <td>78901234</td>
                      <td>19-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>María</td>
                      <td>García</td>
                      <td>67890123</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Ana</td>
                      <td>Rodríguez</td>
                      <td>45678901</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Sebastián</td>
                      <td>Torres</td>
                      <td>12345678</td>
                      <td>19-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Daniel</td>
                      <td>Rodríguez</td>
                      <td>34567890</td>
                      <td>18-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Mateo</td>
                      <td>Rodríguez</td>
                      <td>34567890</td>
                      <td>18-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Santiago</td>
                      <td>García</td>
                      <td>12345678</td>
                      <td>18-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Valentina</td>
                      <td>López</td>
                      <td>90123456</td>
                      <td>17-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Catalina</td>
                      <td>Pérez</td>
                      <td>89012345</td>
                      <td>17-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Nicolás</td>
                      <td>Silva</td>
                      <td>78901234</td>
                      <td>17-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Valeria</td>
                      <td>Pérez</td>
                      <td>01234567</td>
                      <td>16-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Felipe</td>
                      <td>Martínez</td>
                      <td>34567890</td>
                      <td>16-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Juan</td>
                      <td>Martínez</td>
                      <td>56789012</td>
                      <td>16-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Diego</td>
                      <td>Castro</td>
                      <td>67890123</td>
                      <td>16-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Alejandro</td>
                      <td>Martínez</td>
                      <td>89012345</td>
                      <td>15-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Sofía</td>
                      <td>Pérez</td>
                      <td>45678901</td>
                      <td>15-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Ana</td>
                      <td>García</td>
                      <td>23456789</td>
                      <td>15-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Daniela</td>
                      <td>López</td>
                      <td>01234567</td>
                      <td>15-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Gabriela</td>
                      <td>Díaz</td>
                      <td>23456789</td>
                      <td>14-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Martín</td>
                      <td>Sánchez</td>
                      <td>90123456</td>
                      <td>14-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Manuel</td>
                      <td>Díaz</td>
                      <td>78901234</td>
                      <td>14-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Diego</td>
                      <td>López</td>
                      <td>56789012</td>
                      <td>14-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Ana</td>
                      <td>Gómez</td>
                      <td>56789012</td>
                      <td>14-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Laura</td>
                      <td>Gutiérrez</td>
                      <td>67890123</td>
                      <td>13-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Paula</td>
                      <td>Gómez</td>
                      <td>45678901</td>
                      <td>13-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Valentina</td>
                      <td>Díaz</td>
                      <td>23456789</td>
                      <td>13-05-2024</td>
                      <td>1</td>
                      </tr>                                                                                                   
                    </tbody>
                </table>
            </div>

            <div id="historialSkateboards" class="hidden">
                <h3>Historial de Skateboards</h3>
                <p>Aquí se mostrará el historial de skateboards.</p>
                <!-- Añadir contenido relevante del historial de skateboards -->
                <style>
                    .table {
                      border-collapse: separate;
                      border-spacing: 0 10px;
                      width: 100%;
                    }
                    .table th,
                    .table td {
                      padding: 8px;
                      text-align: left;
                      border-bottom: 1px solid #ddd;
                    }
                    .table th {
                      background-color: #f2f2f2;
                      color: black;
                      border-top: 1px solid #ddd;
                    }
                    .table tbody tr:nth-child(even) {
                      background-color: #f2f2f2;
                    }
                    .table tbody tr:hover {
                      background-color: #ddd;
                    }
                  </style>
                  
                  <table class="table">
                    <thead class="thead-dark">
                      <tr>
                        <th scope="col">Total</th>
                        <th scope="col">Alquiladas</th>
                        <th scope="col">Disponibles</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>250</td>
                            <td>50</td>
                            <td>200</td>
                        </tr>
                    </tbody>
                  </table>
                  <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">Cédula</th>
                            <th scope="col">Fecha de Inicio</th>
                            <th scope="col">Duración (días)</th>
                        </tr>
                    </thead>
                    <tbody>
                      <tr>
                      <td>Andrés</td>
                      <td>Pérez</td>
                      <td>90123456</td>
                      <td>19-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Sofía</td>
                      <td>Fernández</td>
                      <td>56789012</td>
                      <td>19-05-2024</td>
                      <td>5</td>
                      </tr>
                      <tr>
                      <td>Lucía</td>
                      <td>González</td>
                      <td>23456789</td>
                      <td>19-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Mateo</td>
                      <td>Hernández</td>
                      <td>89012345</td>
                      <td>19-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Natalia</td>
                      <td>Santos</td>
                      <td>12345678</td>
                      <td>18-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Camila</td>
                      <td>Martínez</td>
                      <td>23456789</td>
                      <td>18-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Juan</td>
                      <td>Pérez</td>
                      <td>78901234</td>
                      <td>18-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Andrés</td>
                      <td>Ruiz</td>
                      <td>89012345</td>
                      <td>18-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Julia</td>
                      <td>Santos</td>
                      <td>01234567</td>
                      <td>18-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Diego</td>
                      <td>González</td>
                      <td>45678901</td>
                      <td>18-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Pedro</td>
                      <td>González</td>
                      <td>45678901</td>
                      <td>17-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Carla</td>
                      <td>Pérez</td>
                      <td>78901234</td>
                      <td>17-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Pablo</td>
                      <td>Ruiz</td>
                      <td>01234567</td>
                      <td>17-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Carlos</td>
                      <td>González</td>
                      <td>34567890</td>
                      <td>17-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Santiago</td>
                      <td>Santos</td>
                      <td>56789012</td>
                      <td>17-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Jimena</td>
                      <td>Ruiz</td>
                      <td>67890123</td>
                      <td>16-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Mateo</td>
                      <td>Fernández</td>
                      <td>12345678</td>
                      <td>16-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Sofía</td>
                      <td>Martínez</td>
                      <td>67890123</td>
                      <td>16-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Carla</td>
                      <td>Díaz</td>
                      <td>78901234</td>
                      <td>16-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Marta</td>
                      <td>Ruiz</td>
                      <td>90123456</td>
                      <td>16-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Jimena</td>
                      <td>Pérez</td>
                      <td>34567890</td>
                      <td>16-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Lucas</td>
                      <td>Ruiz</td>
                      <td>01234567</td>
                      <td>16-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Natalia</td>
                      <td>Ruiz</td>
                      <td>45678901</td>
                      <td>15-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Diego</td>
                      <td>Santos</td>
                      <td>78901234</td>
                      <td>15-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Julia</td>
                      <td>García</td>
                      <td>01234567</td>
                      <td>15-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Elena</td>
                      <td>Pérez</td>
                      <td>34567890</td>
                      <td>15-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Laura</td>
                      <td>Pérez</td>
                      <td>23456789</td>
                      <td>15-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Andrés</td>
                      <td>Martínez</td>
                      <td>67890123</td>
                      <td>15-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Elena</td>
                      <td>Díaz</td>
                      <td>90123456</td>
                      <td>15-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Pedro</td>
                      <td>Pérez</td>
                      <td>78901234</td>
                      <td>14-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Juan</td>
                      <td>Martínez</td>
                      <td>67890123</td>
                      <td>14-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Martín</td>
                      <td>García</td>
                      <td>23456789</td>
                      <td>14-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Marcos</td>
                      <td>López</td>
                      <td>56789012</td>
                      <td>14-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Pedro</td>
                      <td>García</td>
                      <td>12345678</td>
                      <td>14-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Camila</td>
                      <td>Díaz</td>
                      <td>34567890</td>
                      <td>14-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>David</td>
                      <td>Fernández</td>
                      <td>34567890</td>
                      <td>14-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Carla</td>
                      <td>González</td>
                      <td>01234567</td>
                      <td>14-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>Valeria</td>
                      <td>García</td>
                      <td>89012345</td>
                      <td>13-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Santiago</td>
                      <td>García</td>
                      <td>23456789</td>
                      <td>13-05-2024</td>
                      <td>3</td>
                      </tr>
                      <tr>
                      <td>Marta</td>
                      <td>Santos</td>
                      <td>90123456</td>
                      <td>13-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Andrés</td>
                      <td>Díaz</td>
                      <td>89012345</td>
                      <td>13-05-2024</td>
                      <td>2</td>
                      </tr>
                      <tr>
                      <td>David</td>
                      <td>Hernández</td>
                      <td>89012345</td>
                      <td>13-05-2024</td>
                      <td>1</td>
                      </tr>
                      <tr>
                      <td>Valeria</td>
                      <td>Fernández</td>
                      <td>56789012</td>
                      <td>13-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Carla</td>
                      <td>Martínez</td>
                      <td>01234567</td>
                      <td>13-05-2024</td>
                      <td>4</td>
                      </tr>
                      <tr>
                      <td>Lucas</td>
                      <td>Díaz</td>
                      <td>34567890</td>
                      <td>13-05-2024</td>
                      <td>2</td>
                      </tr>                                                                                             
                    </tbody>
                </table>
            </div>
        </div>
        <br>
        <br>
        <br>
    </main>
    <footer>
        <p>&copy; 2024 Cyber Connect Commute</p>
    </footer>
    <script src="JS/script.js"></script>
    <script>
        function mostrarHistorial() {
            const tipoVehiculo = document.getElementById('tipoVehiculo').value;
            document.getElementById('historialBicicletas').classList.add('hidden');
            document.getElementById('historialPatinetas').classList.add('hidden');
            document.getElementById('historialSkateboards').classList.add('hidden');

            if (tipoVehiculo === 'bicicletas') {
                document.getElementById('historialBicicletas').classList.remove('hidden');
            } else if (tipoVehiculo === 'patinetas') {
                document.getElementById('historialPatinetas').classList.remove('hidden');
            } else if (tipoVehiculo === 'skateboards') {
                document.getElementById('historialSkateboards').classList.remove('hidden');
            }
        }
    </script>
</body>

</html>
